### ISSUE TITLE
Layout Friends View

### ISSUE THREAD

**Issue by maurya** [personalcancertoolkit/openmrs-module-patientportaltoolkit#248]
Show a comparable view of friends - confirm

Ask if anonymized data for all other patients can be shown if within age range and similar type of cancer and stage of cancer.

**Comment by uladkasach** [comment]
Note, friends view can be displayed on advice view, rather than in separate view. 

Per last meeting, list 5-10 users in alpha order on advice view which user can choose from to display on graph. Limit user to X (likely ~ 5) users that they can compare to at a time. Consider a "view more" button if user has more than 5-10 budies. Ensure different users are labeled on graph clearly.
