### ISSUE TITLE
When two connections requests come the tool made 2 connections, not just one.

### ISSUE THREAD

**Issue by maurya** [personalcancertoolkit/openmrs-module-patientportaltoolkit#420]
Make sure to check if either a connection or a request has been already created for the same two people before processing the request

**Comment by bmamlin** [comment]
- [ ] Maurya to send a couple additional test accounts to David to try to test/recreate the problem.

**Comment by PhilipAdeoye** [comment]
The problem is actually really easy to recreate.

1. Assuming we have two unconnected accounts: Alex and Kenna
2. Open a window with Alex
3. Open another window (Incognito) with Kenna
4. Request a connection with Alex
5. Request a connection with Kenna
6. Bada bing bada boom - duplicated connections
